name: openid connect
on:
  push:
    branches:
      - main

env:
  ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ID}}:role/${{ secrets.ROLE_ARN }}
  SESSION_NAME: gh-oidc-${{ github.run_id }}-${{ github.attempt }}

jobs:
  connect:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: ${{ env.SESSION_NAME }}
          aws-region: ap-northeast-1
      - run: aws iam list-users
      - run: aws iam create-user --user-name invalid || true